### ISSUE TITLE
Unsupported application permission listed in Delete device doc

### ISSUE THREAD

**Issue by manufz** [microsoftgraph/microsoft-graph-docs-contrib#20]
The Delete device documentation lists Device.ReadWrite.All as a viable application permission although deletion is currently only possible with delegated permissions.

Device.ReadWrite.All description from Azure AD portal: Allows the app to read and write all device properties without a signed in user. Does not allow device creation, device deletion or update of device alternative security identifiers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3a6b91f-5c3a-d92f-a572-fa47ff846e6b
* Version Independent ID: bcf37011-94d5-0dc3-1cc2-d00da6ab9758
* Content: [Delete device - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/device-delete?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/device-delete.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @myra-ramdenbourg
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @manufz for raising this issue. I've been able to delete a device with my app granted only _Device.ReadWrite.All_ application permission. The description seems outdated, but I've filed an internal bug # 2670482 for the product team to align the permission description with the permission capability.  Closing this issue here.

cc @myra-ramdenbourg
