### ISSUE TITLE
Error code: InvalidArgument 

### ISSUE THREAD

**Issue by Kostis-K** [microsoftgraph/microsoft-graph-docs-contrib#203]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bdd1d978-a9fc-b6b0-54c9-6898dc6a1890
* Version Independent ID: 0f543185-509d-4050-bbab-a9d94e1037bc
* Content: [WorksheetCollection: add - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/worksheetcollection-add?view=graph-rest-1.0&tabs=java)
* Content Source: [api-reference/v1.0/api/worksheetcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/worksheetcollection-add.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maisarissi** [comment]
The code snippet was updated based on the new [v6 version](https://github.com/microsoftgraph/msgraph-sdk-java/releases/tag/v6.1.0). You can check more info about the new version in the [v6 announcement blog post](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/).

Please, reopen if the issue is still happening with v6.
