### ISSUE TITLE
Combination of the conditional operator `and` and the lambda operator `any` does not seem to work

### ISSUE THREAD

**Issue by tatsumiQ** [microsoftgraph/microsoft-graph-docs-contrib#8517]
The following request returns no messages even though there are some messages which has both categories 'Orange Category' and 'Red Category'.
```
https://graph.microsoft.com/v1.0/me/messages?$filter=categories/any(c:c eq 'Orange Category') and categories/any(c:c eq 'Red Category')
```

On the other hand, the following request successfully returns the messages whose categories include either 'Orange Category' or 'Red Category', or both.
```
https://graph.microsoft.com/v1.0/me/messages?$filter=categories/any(c:c eq 'Orange Category') or categories/any(c:c eq 'Red Category')
```

It seems that the lambda operator `any` works fine with the conditional operator `or` , but not with `and`.
However, I couldn't find any description of this kind of limitation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ca630f7c-e88d-3b10-4ed1-3574dd415ad2
* Version Independent ID: ca630f7c-e88d-3b10-4ed1-3574dd415ad2
* Content: [Use the filter query parameter to filter a collection of objects - Microsoft Graph](https://learn.microsoft.com/en-us/graph/filter-query-parameter?tabs=http)
* Content Source: [concepts/filter-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/filter-query-parameter.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @tatsumiQ for raising this issue. I've tested the `any` function with the `and` operator and I observed that it works as intended on a different API.

Unfortunately, this forum is only for documentation-related issues but [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/283/microsoft-graph-mail-api) is the best forum to answer this functionality question so I recommend that you raise this question there. You may be requested for a request ID for investigation. Closing this issue here.
