### ISSUE TITLE
GET https://graph.microsoft.com/v1.0/subscriptions , the Api not works at all  , tried lots of time but no subscription list it gives , even passing the correct url

### ISSUE THREAD

**Issue by Ashmita-shri** [microsoftgraph/microsoft-graph-docs-contrib#8582]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c121424-d0a2-017c-e40d-3552ea66915c
* Version Independent ID: 999939fe-62c4-e17c-e0b6-d46ef100ecb5
* Content: [List subscriptions - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/subscription-list.md)
* Product: **change-notifications**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @Ashmita-shri for raising this issue. Unfortunately, this forum is only for documentation-related issues but [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/304/microsoft-graph-change-notifications-api) is the best forum to answer this functionality question. I recommend that you raise this question there and provide request IDs for both the subscription creation request and the read request for investigation. Closing this issue here.
