### ISSUE TITLE
Correct usage of API call when app-only tokens are used

### ISSUE THREAD

**Issue by willfiddes** [microsoftgraph/microsoft-graph-docs-contrib#8628]
When using App-Only tokens to make these requests, we need to mention that a filter is required. Otherwise no results are returned.

For example:
/identityGovernance/privilegedAccess/group/eligibilityScheduleRequests?$filter=principalId eq '{principalId}'
or
/identityGovernance/privilegedAccess/group/eligibilityScheduleRequests?$filter=groupId eq '{groupId}'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e6166d2-994b-24c8-45a0-3310225eab62
* Version Independent ID: ee0e90ca-abf8-426c-b2e9-af009f706178
* Content: [List eligibilityScheduleRequests - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/privilegedaccessgroup-list-eligibilityschedulerequests?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/privilegedaccessgroup-list-eligibilityschedulerequests.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/privilegedaccessgroup-list-eligibilityschedulerequests.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @ilyalushnikov
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @willfiddes for raising this issue․ When you say "no results are returned", do you get an empty response object when you expect results or does the request fail and you get an error code?

cc @weijie-lin to investigate whether the app-only behavior is different from the delegated context․

**Comment by FaithOmbongi** [comment]
Following up internally via email thread․

**Comment by weijie-lin** [comment]
@FaithOmbongi , yes, this is expected behavior. For app-only token call to List schedule requests endpoints, either a filter of principalId or groupId is required to return the corresponding data. Otherwise, an empty response with status code 200 will return. 

For delegated token call to List schedule requests endpoints, if the caller does not include any filter, by default the endpoint will return only the requests with principalId as the caller subject id; which means - by default, returning the requests assigned to the requestor/me.
