### ISSUE TITLE
Get-MgServicePrincipalAppRoleAssignedTo not provide permission assignment details.

### ISSUE THREAD

**Issue by IshRajCodes** [microsoftgraph/microsoft-graph-docs-contrib#8669]
1. 
$params = @{
    "PrincipalId" ="e0b8cf4b-8bcc-4285-b17f-a8c96b844ede" # Id of the managed identity
    "ResourceId" = "dab116c8-c84e-44ee-9b2f-0ce3308c9167" # id of MS Graph
    "AppRoleId" = "dc50a0fb-09a3-484d-be87-e023b12c6440" # app role id.
}

2.
New-MgServicePrincipalAppRoleAssignedTo -ServicePrincipalId "e0b8cf4b-8bcc-4285-b17f-a8c96b844ede" -BodyParameter $params
# This creates a new api permissions.

DeletedDateTime Id                                          AppRoleId                            CreatedDateTime     PrincipalDisplayName
--------------- --                                          ---------                            ---------------     --------------------  
                S8-44MyLhUKxf6jJa4RO3pRWQ1NbMWVEm5_T4YSdxlo dc50a0fb-09a3-484d-be87-e023b12c6440 04/10/2023 17:04:38 dsppgblpam01

3. 
Get-MgServicePrincipalAppRoleAssignedTo -ServicePrincipalId "e0b8cf4b-8bcc-4285-b17f-a8c96b844ede" 

# This does not provide the permission assignment details in step 2, as mentioned in the article.

4.  
Get-MgServicePrincipalAppRoleAssignment -ServicePrincipalId "e0b8cf4b-8bcc-4285-b17f-a8c96b844ede"

# This provides the details of the permission assigned in step 2.

Question: What is the difference between New-MgServicePrincipalAppRoleAssignedTo and New-MgServicePrincipalAppRoleAssignment methods ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78849f24-c5cb-8843-6b82-b8e3fb4c0dcf
* Version Independent ID: 78849f24-c5cb-8843-6b82-b8e3fb4c0dcf
* Content: [Grant or revoke API permissions programmatically - Microsoft Graph](https://learn.microsoft.com/en-us/graph/permissions-grant-via-msgraph?tabs=http)
* Content Source: [concepts/permissions-grant-via-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/permissions-grant-via-msgraph.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @IshRajCodes for raising this issue.

The reason you didn't get the assignments with this request is that you used the wrong ID here. The request requires the ID of the *resource* service principal, in your case `dab116c8-c84e-44ee-9b2f-0ce3308c9167`, the ID of Microsoft Graph, as opposed to the _client_ service principal, which you used.

<img width="615" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/14026935/6c8372e1-63dd-40e4-8371-f12337b9e059">


And that's also why your last query with approleassignment worked, because you used the ID of the _client service principal_.

To answer your last question:

> Question: What is the difference between New-MgServicePrincipalAppRoleAssignedTo and New-MgServicePrincipalAppRoleAssignment methods ?

Great question.

- appRoleAssignedTo is saying "I want to know the apps that have been assigned app roles that I expose" - in this case, the "I" actor is the _resource service principal_ that exposes the app roles.
- appRoleAssignments is saying "I want to know the app roles that I've been assigned" - in this case, the "I" actor is the _client service principal_.


Hope this answer resolves your issue.
