### ISSUE TITLE
Capitalization of the received `skiptoken` param is inaccurate

### ISSUE THREAD

**Issue by gal-r** [microsoftgraph/microsoft-graph-docs-contrib#8697]
Hello,

I have noticed while using the Graph API that despite both this document and the explorer showcasing the returned value in `@odata.nextLink` to include the skip token in the format of either `skiptoken` or `skip` in the URL's searchparams, when querying `/users` and `/groups` I receive the skip token in the format of `skipToken` in camelCase.

This mismatch between the explorer/docs and the actual returned value cost me some valuable work time so I figured it's best to update it wherever possible.

Currently using version `3.0.5` of the `@microsoft/microsoft-graph-client` client to execute my requests if that might be relevant.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7e1ac6d-b2ee-c495-3194-f2895e26945e
* Version Independent ID: 73f817df-a829-e265-c932-7ae8b3f3e918
* Content: [Paging Microsoft Graph data in your app  - Microsoft Graph](https://learn.microsoft.com/en-us/graph/paging?tabs=http)
* Content Source: [concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/paging.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @gal-r for raising this issue. I've investigated it and can confirm that the REST API returns the lowercase version.
However:
1) If you test the REST API requests, either case works.
2) We recommend as a best practice that you assume query parameters aren't case-sensitive. See [here](https://learn.microsoft.com/en-us/graph/traverse-the-graph?tabs=http#microsoft-graph-api-metadata).

Hope this helps address how you can handle the mismatch.

<img width="540" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/14026935/fe75ba3d-ac46-4f27-a7a5-6857340badb4">

Also, feel free to file this issue in the C# SDK repo so that the team can advise further. I'll proceed to close this issue here because it's not a documentation issue.
