### ISSUE TITLE
accountEnabled property is not provided by directoryObject: getByIds

### ISSUE THREAD

**Issue by ManuelHaas** [microsoftgraph/microsoft-graph-docs-contrib#8798]
In the example Response there is the property `accountEnabled` listet for the two user objects, but this property is not provided by `directoryObject: getByIds` method!
Even the documentation of `accountEnabled` states: true if the account is enabled; otherwise, false. This property is required when a user is created. **Returned only on $select**. Supports $filter (eq, ne, not, and in).

2nd error: Under Permission it says for Application: Directory.Read.All as least priviledge but User.Read.All is sufficient to load user objects.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 652f070a-a126-9add-13db-e35250b8b86c
* Version Independent ID: d256be5b-8466-385f-32a4-2d9fd9a89886
* Content: [directoryObject: getByIds - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/directoryobject-getbyids?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/directoryobject-getbyids.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/directoryobject-getbyids.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @ManuelHaas for raising this issue. Yes, you're right. **accountEnabled** isn't returned by default in v1 - this must be a copy-paste error from beta.

On the permission issue, yes, technically, User.Read.All would work, for example. But because the permission doesn't authorize you to see groups or devices for example, you might see only limited info relating to the other directory objects. Please note the comment after the permissions table for more details. However, when you use *Directory.Read.All*, you have a holistic view of all directory objects the API returns.
