### ISSUE TITLE
Where to find correct role id for an assignment to an administrative unit

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs-contrib#8812]
The request body contains property `roleId`, but it's not clear where to find the correct value.
Let's say I want to assign the `User Administrator` role.

The endpoint `GET /v1.0/directoryRoles` returns the `User Administrator` role with one id

    {
        "id": "947ccf23-ee27-4951-8110-96c62c680311",
        "deletedDateTime": null,
        "description": "Can manage all aspects of users and groups, including resetting passwords for limited admins.",
        "displayName": "User Administrator",
        "roleTemplateId": "fe930be7-5e62-47db-91af-98c3a49a38b1"
    }

But the endpoint `GET v1.0/roleManagement/directory/roleDefinitions` returns the `User Administrator` role with another id

    {
        "id": "fe930be7-5e62-47db-91af-98c3a49a38b1",
        "description": "Can manage all aspects of users and groups, including resetting passwords for limited admins.",
        "displayName": "User Administrator",
        "isBuiltIn": true,
        "isEnabled": true,
        "resourceScopes": [
            "/"
        ],
        "templateId": "fe930be7-5e62-47db-91af-98c3a49a38b1"
    }

Could please add info where to find the correct role id?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b34c1a6-e738-c66e-85b6-5a813dacc0b2
* Version Independent ID: 7a586d2e-260b-fa2d-5981-18797d37ff02
* Content: [Add a scopedRoleMember - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/administrativeunit-post-scopedrolemembers?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/administrativeunit-post-scopedrolemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/administrativeunit-post-scopedrolemembers.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @DougKirschner
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @MartinM85 for raising this issue.

Please note the two endpoints are different. So, the two **id** values are expectedly different. However, they refer to the same role, in your case, "User Administrator". 

If you're working with the `/directoryRoles` API endpoints, then all references of **id** you get from calling these `/directoryRoles`; Same case for the `/roleManagement/directory/roleDefinitions` endpoint.

Because both APIs relate to the same roles, **roleTemplateId** in `/directoryRoles` matches **templateId** in `/roleManagement/directory/roleDefinitions` - both are the same values you see from the [Microsoft Entra built-in roles reference](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference?toc=%2Fgraph%2Ftoc.json&view=graph-rest-1.0) and also on the Microsoft Entra portal.

That aside, I recommend you use `/roleManagement/directory/*` APIs, which are the newer versions of the APIs for managing the RBAC provided by Microsoft Entra. This endpoint also exposes a lot more capabilities compared to the `/directoryRoles` endpoint. `/directoryRoles` will be deprecated in favor of `/roleManagement/directory/*` in the near future.
