### ISSUE TITLE
Permissions required to use this call

### ISSUE THREAD

**Issue by courtimus** [microsoftgraph/microsoft-graph-docs-contrib#8921]
[After some testing, it appears in order for a user to actually receive any data back from this call, the user has to be a member of the "Admin Agents", otherwise the value will just return empty. I'm unsure if this is a bug or if it's by design. If it's by design, it should be documented.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f437c57-63d5-63ef-c4d3-df25d9988a82
* Version Independent ID: e581dd3c-8695-034c-7636-6942b093869e
* Content: [Get delegatedAdminRelationship - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/delegatedadminrelationship-get.md)
* Product: **partner-customer-administration**
* Technology: **microsoft-graph**
* GitHub Login: @koravvams
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by koravvams** [comment]
Hi @courtimus,

This is by design, some APIs like get customers, service management details will work with "Admin Agents" membership but other APIs need "Admin Agents" membership must. Returning success with empty response is by-design. "Admin Agents" membership permission is documented in partner center docs - https://learn.microsoft.com/en-us/partner-center/gdap-obtain-admin-permissions-to-manage-customer.
