### ISSUE TITLE
Use correct API version in Graph subscription lifecycle

### ISSUE THREAD

**Issue by zhiweiv** [microsoftgraph/microsoft-graph-docs-contrib#8960]
In the example(https://learn.microsoft.com/en-us/graph/webhooks-lifecycle?tabs=http#actions-to-take), it uses beta APIs, which get confusing, these APIs have 1.0 version(https://learn.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&tabs=http).

Same issue in https://learn.microsoft.com/en-us/azure/event-grid/subscribe-to-graph-api-events?context=graph%2Fcontext&tabs=http#how-to-renew-a-microsoft-graph-api-subscription.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a8738b3-f7c3-b49e-4a1f-d4cf7e92134e
* Version Independent ID: 12fb1cbe-ecab-1be3-b137-bbc13ba6c40b
* Content: [Reduce missing change notifications and removed subscriptions - Microsoft Graph](https://learn.microsoft.com/en-us/graph/webhooks-lifecycle?tabs=http)
* Content Source: [concepts/webhooks-lifecycle.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/webhooks-lifecycle.md)
* Product: **change-notifications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @zhiweiv for raising this issue. I've updated the first instance to use the v1.0 APIs because the feature is available in v1.0.

For the Event Grid article, support for change notifications via Event Grid is currently in public preview (beta). We'll keep referencing the beta API in the docs until support becomes generally available (v1.0).
