### ISSUE TITLE
Sample response doesn't match invitation, and additional info needed

### ISSUE THREAD

**Issue by bretthacker** [microsoftgraph/microsoft-graph-docs-contrib#8968]
The invitation body:
{
  "invitedUserEmailAddress": "admin@fabrikam.com",
  "inviteRedirectUrl": "https://myapp.contoso.com"
}

The response includes this:
  "invitedUserDisplayName": "Fabrikam Admin",

How did "Fabrikam Admin" get assigned? That name would need to be passed in the invitation, so add "InvitedUserDisplayName" to the invitation body request.

Second, can the document flesh out how to submit an invitation that includes setting givenName and surName? I've tried like this but it's not accepted:

var dict = new Dictionary<string, object>
{
    { "givenName", invite.FirstName },
    { "surName", invite.LastName }
};

var invitation = new Invitation
{
    InvitedUserEmailAddress = invite.Email,
    InviteRedirectUrl = replyUrl,
    InvitedUserDisplayName = $"{invite.FirstName} {invite.LastName}",
    InvitedUserMessageInfo = info,
    SendInvitationMessage = invite.SendInvitation,
    AdditionalData = dict
};

Please add details on what "AdditionalData" properties can be added and how to construct them.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f51b2654-e447-d495-2788-d6d5b13402b4
* Version Independent ID: 32183c44-363a-a028-a3d9-390b99bffc8b
* Content: [Create invitation - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/invitation-post?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/invitation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/invitation-post.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @ppolkadots
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @bretthacker for raising this issue.

For the first question: The response object in the documentation shows the status as `Completed` meaning the guest has redeemed their invitation. As a result, the **invitedUserDisplayName** property got autofilled with the user's displayName data from their home tenant.

On the second: No, you can't supply the givenName and surname properties because they are not part of [the invitation object](https://learn.microsoft.com/en-us/graph/api/resources/invitation?view=graph-rest-1.0#properties). After redemption, these properties on the user object are also autofilled with corresponding data from the user's home tenant. You can also update them in your tenant if you wish.

**Comment by bretthacker** [comment]
I have never seen the givenName or surname properties populated from the home tenant. Additionally, it's my experience that if I don't supply the invitedUserDisplayName property, it sets null:

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/693701/75be1838-a490-455c-a04b-1dbefc595474)

Please review this response and adjust accordingly. This documentation is in error.

**Comment by bretthacker** [comment]
With regards to the username and surname, this is in error as well; these are NOT autofilled from the home tenant:
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/693701/66e519b4-809f-48ac-8774-9e4e1f0757f7)

**Comment by bretthacker** [comment]
As info, the invited object here is from another Entra tenant, not Live. These properties are populated in the home tenant.

**Comment by FaithOmbongi** [comment]
I stand corrected on givenName and surname - those are set to `null`. I've corrected my initial reply.

>Additionally, it's my experience that if I don't supply the invitedUserDisplayName property, it sets null

Yes, correct - but only while the invitation is in a `PendingAcceptance` status. Please note the response in the doc is for a `Completed` state. If you check the user object after successful redemption (There's no API to check an invitation object), their displayName got populated with the same value the user has in their home tenant. My repro:
- After creating the invitation and it's in a `PendingAcceptance `status:
   - **invitedUserDisplayName** of the [invitation](https://learn.microsoft.com/en-us/graph/api/resources/invitation?view=graph-rest-1.0#properties) object is `null` 
   - **displayName** of the [user](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties) object is filled with the username part of the **invitedUserEmailAddress** value that you specified in the invitation.
- After redemption, while you can't see the pending invitation through the /invitations endpoint, you can see the user object and
   - the **displayName** of the [user](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties) object has changed to whatever value the user has in the home tenant. This change occurs because part of the invitation redemption request is a consent request for the user to grant the guest tenant access to receive and use their profile data.

In case the [Create invitation](https://learn.microsoft.com/en-us/graph/api/invitation-post?view=graph-rest-1.0&tabs=http#response-1) example response causes confusion, I'm happy to update to one with a `PendingAcceptance` state.

**Comment by bretthacker** [comment]
Ah, OK, that's fair. In our use case, we invite users that may take a while before they redeem, so we go ahead and assign the invitedUserDisplayName in the invitation and that assignment is taken and applied. It's interesting that upon redemption, the displayName would be returned by the home tenant, but not givenName or surname.

Regarding the sample code, I'd think that given the fact that an initial invitation response is by definition in a PendingAcceptance state since the user couldn't have consented yet, it would be useful to have the response object reflect the expected state - it won't have the displayName assignment yet. That's what threw me off; that friendly name couldn't have been known yet at that stage in the workflow. Thanks for engaging here.

**Comment by bretthacker** [comment]
Regarding the other question, the Invitation object does expose the AdditionalData dictionary, and states that it's used for getting OR setting additional data. If givenName or surname aren't accepted there, it might be useful in the doc to indicate what properties ARE eligible to be assigned there.

**Comment by FaithOmbongi** [comment]
OK, I'll update the example response.

> Regarding the other question, the Invitation object does expose the AdditionalData dictionary, and states that it's used for getting OR setting additional data. If givenName or surname aren't accepted there, it might be useful in the doc to indicate what properties ARE eligible to be assigned there.

Allow me to investigate further and update the documentation with properties that can be configured while creating the invitation.

**Comment by bretthacker** [comment]
Thanks, it would be helpful as I'm now having to create the invitation, pause a few seconds, then send an update call to set these properties. Ideally any user property would be eligible, including custom properties.
