### ISSUE TITLE
riskEventType values question

### ISSUE THREAD

**Issue by WarrenW159** [microsoftgraph/microsoft-graph-docs-contrib#9001]
Hello,

Should the name of the riskEventType value have an associated numerical value?  For example, when looking in the AADSignInEventsBeta schema in MS Defender for O365, the riskEventType column has a value (i.e., [101], [210]), without any link to what that value represents.  I am thinking that a riskEventType of 210 correlates with 'Anomalous token' risk event type.  

There's no way to tell for sure since this information is not found on https://learn.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-1.0#riskeventtype-values as I might have expected.  Is there a reason for this?

Best,
W

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ce56fe4-b5f4-cdde-1f35-39091aaa6303
* Version Independent ID: b07140db-8b54-e375-bbb8-1506aa0e616f
* Content: [riskDetection resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/riskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/riskdetection.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @ebasseri
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ebasseri** [comment]
@tracyshi I think the answer is "no," correct?

**Comment by FaithOmbongi** [comment]
Thank you @WarrenW159 for raising this issue. The answer is no. If you're seeing integer values instead of the strings described in the documentation, then this is a functionality bug.

Unfortunately, this forum is only for documentation-related issues but [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) is the best forum to file this functionality bug so it can be investigated and resolved. You may be requested for a request ID for investigation. Please file the bug at [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph). Closing this issue here.
