### ISSUE TITLE
The documentation incorrectly states that duplicate subscriptions are not allowed

### ISSUE THREAD

**Issue by hesperanca** [microsoftgraph/microsoft-graph-docs-contrib#9039]
[Enter feedback here]

Under the "Duplicate subscription behaviour" the documentation states that duplicate subscriptions are not allowed. This is incorrect (at least for SharePoin list subscriptions). I just managed to create a duplicate subscription for the same SharePoint list, with the same ChangeType, ApplicationID and CreatorId without getting any errors.
 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f20de46-dc28-3cde-642a-4a7fb7b2f454
* Version Independent ID: be834d56-fb0c-0f16-31f8-287221ba6cc4
* Content: [Create subscription - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/subscription-post-subscriptions.md)
* Product: **change-notifications**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @hesperanca - I think this issue should be investigated further. Can you file it at [Microsoft Graph Q&A](https://aka.ms/askgraph) and provide a request ID (or the two subscription IDs) for further investigation? Once the issue is investigated and a doc update is identified, we'll update the documentation.

cc @keylimesoda for visibility.
