### ISSUE TITLE
Missing reference to policyId in rule set

### ISSUE THREAD

**Issue by glennvanrymenant** [microsoftgraph/microsoft-graph-docs-contrib#9046]
why is there no reference to the policy in the management policy rule set output?

I list the rules for a policy:

v1.0/policies/roleManagementPolicies/<policyId>/rules 

I receive a collection of rule objects but no reference to the policy, so I have to add that context myself when I dump all rule sets for all roles in a variable and have to retrieve the rule set for a specific policyId.

Typically, a foreign key is foreseen to correlate (based on my experience with other Graph endpoints).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d593d5f3-bd7f-e43c-87cc-45741c2220de
* Version Independent ID: 65f75714-d1bb-9f40-10b8-76676c360076
* Content: [List rules (for a role management policy) - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/unifiedrolemanagementpolicy-list-rules?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/unifiedrolemanagementpolicy-list-rules.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/unifiedrolemanagementpolicy-list-rules.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @rkarim-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @glennvanrymenant for asking this question.

As per the schema, there's no reference to the policy from a rule, but there's a reference to rules from a policy (see [Example 2: Retrieve the role management policies that apply to PIM for Microsoft Entra roles and expand the associated rules](https://learn.microsoft.com/en-us/graph/api/policyroot-list-rolemanagementpolicies?view=graph-rest-1.0&tabs=http#example-2-retrieve-the-role-management-policies-that-apply-to-pim-for-microsoft-entra-roles-and-expand-the-associated-rules)). This is because PIM attaches multiple rules to a policy as opposed to multiple policies to a rule. Hope this clarifies the API design.
