### ISSUE TITLE
Get-MgRoleManagementDirectoryRoleAssignmentSchedule -Filter "PrincipalID eq {principalid}

### ISSUE THREAD

**Issue by VincentJdeB** [microsoftgraph/microsoft-graph-docs-contrib#9056]
Hello,
I want to get all eligible and all assigned Privileged Access Group assignments for a user account.

I am getting the error "Attempted to perform an unauthorized operation" when I use the command "Get-MgRoleManagementDirectoryRoleAssignmentSchedule -Filter "PrincipalID eq {principalid}" or "Get-MgRoleManagementDirectoryRoleEligibilitySchedule -Filter "PrincipalID eq {principalid}".

Any help is welcome,
Vincent
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72701ea1-336c-ae40-2897-332b51159bc1
* Version Independent ID: b15d1fad-1029-f63e-3e3c-7fa239d03f25
* Content: [List assignmentSchedules - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/privilegedaccessgroup-list-assignmentschedules?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/privilegedaccessgroup-list-assignmentschedules.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/privilegedaccessgroup-list-assignmentschedules.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @ilyalushnikov
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @VincentJdeB for raising this issue.

Please confirm that aside from the Microsoft Graph permissions, you have [Microsoft Entra role](https://learn.microsoft.com/en-us/graph/api/privilegedaccessgroup-list-assignmentschedules?view=graph-rest-1.0&tabs=http#permissions)s that are listed on the page. If you still get the error, please file the issue at [Microsoft Graph Q&A](https://aka.ms/askgraph) and provide a request ID so the issue can be investigated.

I'll close this issue here because this is a forum for doc-only issues. Should the investigation conclude that updates are required for the documentation, we'll make the doc updates. Thank you.
