### ISSUE TITLE
Very poorly written 

### ISSUE THREAD

**Issue by gkranasinghe** [microsoftgraph/microsoft-graph-docs-contrib#9087]
[Enter feedback here]

How are we supposed to understand where the [InstantiatePostRequestBody](https://github.com/microsoftgraph/msgraph-sdk-python/blob/main/msgraph/generated/application_templates/item/instantiate/instantiate_post_request_body.py#L8-L47)  can be imported 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9067ae9-89d0-5854-7327-856d930e7712
* Version Independent ID: e0ed6a1b-34bc-55a2-b4ca-61fe3f8ca367
* Content: [Use Microsoft Graph APIs to configure SAML-based single sign-on - Microsoft Graph](https://learn.microsoft.com/en-us/graph/application-saml-sso-configure-api?tabs=python%2Cpowershell-script)
* Content Source: [concepts/application-saml-sso-configure-api.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/application-saml-sso-configure-api.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by jasonjoh** [comment]
Sorry for the trouble @gkranasinghe. This is an issue with our snippet generator creating invalid import statements. I've filed that issue here: https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1954. That issue will need to be fixed to get this document updated. Closing this issue in favor of the other one.

In the meantime, the correct import is:

```python
from msgraph.generated.application_templates.item.instantiate.instantiate_post_request_body import InstantiatePostRequestBody
```
