### ISSUE TITLE
Incorrect Syntax - identities/any(i:i/issuer)

### ISSUE THREAD

**Issue by Mike-Crowley** [microsoftgraph/microsoft-graph-docs-contrib#9104]
In attempt to list B2B objects in a tenant, This syntax seems reasonable and consistent with the documentation on this page, however when we query it:

    $Uri = @'
    v1.0/users?$filter=identities/any(i:i/issuer eq 'ExternalAzureAD')&$select=identities&$count=true
    '@
    Invoke-MgGraphRequest -Uri $Uri -Headers  @{ConsistencyLevel = "eventual"}

The following error is returned:
> HTTP/1.1 400 Bad Request
> {"error":{"code":"Request_UnsupportedQuery","message":"Unsupported query on property 

Graph Explorer has a similar error:
> "code": "Request_UnsupportedQuery",
 > "message": "Unsupported query on property 'ObjectIdentity'.",

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/6467813/6b2f5e7f-1e27-4b5f-a578-02d38ec420f7)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36cbb5db-1ff4-a7b9-819a-4efb704007ce
* Version Independent ID: 7e6f3bbd-f364-0ff8-2e14-977860bd7ff9
* Content: [Advanced query capabilities on Microsoft Entra ID objects - Microsoft Graph](https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http)
* Content Source: [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/aad-advanced-queries.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by Licantrop0** [comment]
Hi @Mike-Crowley, thanks for reporting this; I'm the PM responsible for the Advanced Queries.

The [documentation on our Advanced Query](https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http#:~:text=identities/any(i%3Ai/issuer)) page is missing extra info on this particular property, and I'm going to address this issue.

Due to internal architecture complexities, the only supported values for filtering on `issuer` properties alone are: `google.com`, `facebook.com`, `mail`, `phone`. Filtering on `ExternalAzureAD` will return an empty array while there could be users matching that condition in your tenant.
See [this documentation](https://learn.microsoft.com/en-us/graph/api/resources/objectidentity?view=graph-rest-1.0#:~:text=Filtering%20on%20issuer%20alone%20is%20supported%20for%20the%20following%20values%3A%20google.com%2C%20facebook.com%2C%20mail%2C%20and%20phone) for more details.  

Moreover, `identities/issuer` property **is not currently supported by the Advanced Queries**, that's why you are seeing an error when you add `$count=true` and `ConsistencyLevel=eventual` header to your query.

Could you please give us more details on what you are trying to achieve and what your scenario is, so we can prioritize this appropriately in our backlog?

**Comment by Mike-Crowley** [comment]
Thanks for the detailed response. It seems even the people who built the Entra Portal are confused about this, as they only offer an `==` operator and customers get an error no matter what they try to do.

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/6467813/d3edfaad-e359-448c-887d-74429f72948b)

I did see that other article and was wondering it it might be relevant, but didn't realize adding the `count` parameter changed the query type to advanced (it seems to be ok to leave `ConsistencyLevel`).

With your feedback, I got this revision to work:

    $Uri = @'
    v1.0/users?$filter=identities/any(i:i/issuer eq 'mail')&$select=userprincipalname,identities
    '@
    $Request = Invoke-MgGraphRequest -Uri $Uri -Headers  @{ConsistencyLevel = "eventual"}

    $Request.value

As for what I'm trying to accomplish: I want to build some tooling to quickly assess the various types of external users within a tenant. There are complexities when designing external user relationships, authentication settings, etc, which would benefit from reporting, and user normalization; I was hoping to avoid a bunch of client-side filtering.

**Comment by Mike-Crowley** [comment]
Is there a way to list B2B user objects? It looks like we can't look for `#EXT#@` in the UPN either, since its in the middle of a string.

**Comment by Licantrop0** [comment]
Thanks again for reporting the Entra Portal error, I sent this bug to the right owners.
It's ok to leave ConsistencyLevel eventual, just be aware that you will not have a read-after-write consistency (e.g. if your script adds a new user, then you will not be able to immediately see it with that query).  

The good news is that you can filter B2B objects with a workaround! 😊  

Because the userPrincipalName will always have the syntax: `{originalUPN_with_Underscore}#EXT#@{YourTenantDomain}`  
and the B2B objects are `Member`, you can take advantage of the `endsWith` filter operator from the **Advanced Queries** and do this:

`$filter=userType eq 'Member' and endsWith(userPrincipalName, '%23EXT%23%40{YourTenantDomain}')`

>Note : `%23EXT%23%40` (is just `#EXT#@` urlencoded)
> Don't forget `$count=true` and the `ConsistencyLevel=eventual` header

[Try here in Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24filter%3DuserType%2Beq%2B'Member'%2Band%2BendsWith(userPrincipalName%2C%2B'%2523EXT%2523%2540M365x214355.onmicrosoft.com')%26%24select%3Did%2CuserPrincipalName%2CuserType%26%24count%3Dtrue&method=GET&version=beta&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)

**Comment by Mike-Crowley** [comment]
Thanks for the advice on setting `ConsistencyLevel=eventual` unnecessarily - but b2b objects [can have](https://learn.microsoft.com/en-us/entra/external-id/authentication-conditional-access#assigning-conditional-access-policies-to-external-user-types) a `UserType` of `Member` or `Guest`. Also, unfortunately, I'm looking at a tenant right now that has guests with the onmicrosoft domain and also their default domain. Maybe other tenants have even more variety. 

Perhaps the default domain was changed at some point in their tenant. Because its possible to change the onmicrosoft domain and also change the default domain, this may not be a reliable approach. 

I'll just use client side filtering and keep an eye out for better functionality with the identities field.

**Comment by Licantrop0** [comment]
Ah, you're absolutely right: external identities can indeed have a broader range of configurations, sorry if I overlooked the complexities in my previous response.

Maybe filtering on [creationType](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta#:~:text=%2C%20in).-,creationType,-String) could be a reliable solution?

**Comment by Mike-Crowley** [comment]
Unfortunately, that still doesn't work. 

e.g.
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/6467813/1d7a29a0-71cd-43da-b76d-8c72ce2a0343)


I'll just use client side filtering. Hopefully you can address the architecture issue with the identities at some point. Thanks for your insight and time!
