### ISSUE TITLE
User.Export.All - application level permissions 

### ISSUE THREAD

**Issue by sylvainrandierloreal** [microsoftgraph/microsoft-graph-docs-contrib#9159]
Hello,

Regarding the User.Export.All API permission,
When permission is application level, there is not necessarily a user logged in.
So I suspect there is an error in the description of the application permission (I see it is just a copy of the delegated permission so might have been a copy/paste error) 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9edcc46d-c145-fad7-a54c-52c21f05ab7c
* Version Independent ID: 8b6bcf33-b048-2d3c-33b5-5a3dd5d25a75
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://learn.microsoft.com/en-us/graph/permissions-reference)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/permissions-reference.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @sylvainrandierloreal for reporting this discrepancy. 

The permissions description is read from an internal data source that's also published through the [Microsoft Graph service principal](https://developer.microsoft.com/en-us/graph/graph-explorer?request=servicePrincipals%3F%24filter%3DdisplayName%2Beq%2B'Microsoft%2BGraph'&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com). Therefore, I've filed internal bug 2853437 that's assigned to @yyuank to fix the description. The changes will be propagated downstream to the docs within 48 hours of the fixes.

I'll close this issue here since it's a product bug.
