### ISSUE TITLE
Missing documentation for cloudClipboard

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs-contrib#9204]
In the Graph Explorer and in the Graph SDKs, I can call the endpoint

`GET https://graph.microsoft.com/v1.0/me/cloudClipboard/items`

But there is no documentation for the property/relationship `cloudClipboard`, whether it's read-only or also writable.

Now, the endpoint returns the error 409

```
{
    "error": {
        "code": "UnknownError",
        "message": "{\"ErrorCode\":25,\"ErrorMessage\":\"This user is not eligible for cloud clipboard requests as of now.\"}",
        "innerError": {
            "date": "2024-03-01T06:05:47",
            "request-id": "f464bee7-d1bd-4d64-a29b-b800a6eb4976",
            "client-request-id": "8e37fcee-30f4-0002-cc34-d837d37d3be7"
        }
    }
}
```

From the error message it's not clear whether the requests are currently not allowed or if I need some permission/license to make it work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi 
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @MartinM85 for raising this issue.

Unless there's API documentation available on learn.microsoft.com/graph, we don't consider the API as publicly available. So the error means the requests are currently not allowed because the API isn't available to the public as yet.

The **cloudClipboard** relationship is showing up in the SDKs because [the object is available in the public schema](https://graph.microsoft.com/beta/$metadata).  However, it's the combination of available schema _and_ documentation that make the feature officially live.
