### ISSUE TITLE
GroupMember.ReadWrite.All GroupMember.Read.All documentation

### ISSUE THREAD

**Issue by kjellmanj** [microsoftgraph/microsoft-graph-docs-contrib#9224]
Current documentation text
GroupMember.Read.All for application access:
Allows the app to read memberships and basic group properties for all groups without a signed-in user.

GroupMember.ReadWrite.All for application access:
Allows the app to list groups, read basic properties, read and update the membership of the groups this app has access to without a signed-in user. Group properties and owners cannot be updated and groups cannot be deleted.

My query:
GroupMember.Read.All

I think the following text "Allow the app to list groups, " is missing, as it allows to list all groups with basic properties.
GroupMember.ReadWrite.All:
What does it really mean "update the membership of the groups this app has access to without a signed-in user".

Will access by default provide write access to something (as it is named GroupMember.ReadWrite.All) or do we explicitly need to grant access for write?
Is access to be granted via service principal as owner of the group? Via Administrative unit or some other way?
Documentation is very unclear around above. A small additional section would be good to have as the other permission (Group.Read.All) actually allows very wide access as Teams content can be access by the application.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9edcc46d-c145-fad7-a54c-52c21f05ab7c
* Version Independent ID: 8b6bcf33-b048-2d3c-33b5-5a3dd5d25a75
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://learn.microsoft.com/en-us/graph/permissions-reference)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/permissions-reference.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by yuhko-msft** [comment]
Hey @FaithOmbongi - 

1. I agree to update GroupMember.Read.All to be more specific - Allows the app to list groups, read basic properties, and read the membership of the groups this app has access to without a signed-in user.
2. **Regarding What does it really mean "update the membership of the groups this app has access to without a signed-in user".** It means modifying objects in a group.
3. Will access by default provide write access to something (as it is named GroupMember.ReadWrite.All) or do we explicitly need to grant access for write? Is access to be granted via service principal as owner of the group? Via Administrative unit or some other way? **If it's app-only access, it's for an app not for any user object. I don't quite understand the issue here tho.** In app-only "Group.Read.All", we only says "Allows the app to read group properties and memberships, and read conversations for all groups, without a signed-in user."

**Comment by FaithOmbongi** [comment]
Thanks @yuhko-msft, I've filed an internal bug 2864308 for your team with the suggested change.
