### ISSUE TITLE
group update c# sample not doing anything

### ISSUE THREAD

**Issue by ssteiner** [microsoftgraph/microsoft-graph-docs-contrib#923]
I'm trying to update a group using the C# SDK v5.21.0. here's my code

```
Microsoft.Graph.Models.Group updateGroup = new();
updateGroup.Description = "new Description";
updateGroup.DisplayName = "new displayname";
rollbackGroup.MailNickname = "newNickname";

var updatedGroup = await graphServiceClient.Groups[id].PatchAsync(updateGroup ).ConfigureAwait(false);
```

That completes successfully, but the returned group is unchanged. Looking at what is being sent over the wire, it's an empty json. So, either the example is wrong or there's a bug in the SDK.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9552ff12-2b05-3a95-978a-061605f38404
* Version Independent ID: ed70a9f8-9b47-7d73-7188-c7456a4b558b
* Content: [Update group - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/group-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-update.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/group-update.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ssteiner** [comment]
As per [this bug I filed on the .net SDK](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2064) it seems to be a syntax issue - so the documentation could be updated to the syntax in the linked bug and it would be okay.

**Comment by FaithOmbongi** [comment]
Thank you @ssteiner for raising this issue. I see you raised the same issue in the SDK repo, which helps us expedite the investigation and resolution - thank you. The code snippets are autogenerated so updating the sample manually will just get it overwritten in the next weekly refresh. I'll proceed to close this issue here because it's not a docs issue, but we'll track it through the SDK repo via the bug you filed https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2064.
